language: android
jdk: openjdk17
dist: focal

before_install:
  - chmod +x gradlew
  - yes | sdkmanager --licenses
  - sdkmanager "build-tools;35.0.0" "platforms;android-35"

script:
  - ./gradlew clean testDebugUnitTest jacocoTestReport coveralls